apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-function
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: python-function
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
