apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-function
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: python-function
spec:
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
  build:
    env:
      - name: BP_FUNCTION
        value: func.main
