apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-fun
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: hello-fun
spec:
  build:
    env:
      - name: BP_NATIVE_IMAGE
        value: "false"
      - name: BP_JVM_VERSION
        value: "17"
      - name: BP_MAVEN_BUILD_ARGUMENTS
        value: "-Pnative -Dmaven.test.skip=true --no-transfer-progress package"
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main