apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-function
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-function
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/sample-accelerators/node-functions-accelerator.git
