apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: java-function
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: java-function
spec:
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
  build:
    env:
      - name: BP_FUNCTION
        value: functions.Handler
      - name: BP_JVM_VERSION
        value: "17"