apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: my-java-fn
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: my-java-fn
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/sample-accelerators/java-functions-accelerator.git
  build:
    env:
      - name: BP_FUNCTION
        value: functions.Handler