name: "Scan"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '45 4 * * *'
  workflow_dispatch:

jobs:
  analyze:
    name: Scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tool: [ 'grype' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Instal tools
      if: matrix.tool == 'grype'
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin

    - name: Build
      run: ./mvnw -B package

    - name: Perform scanning
      if: matrix.tool == 'grype'
      run: grype --fail-on high --config ./grype.yaml ./target/
