apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: react-test-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test-react
spec:
  params:
    - name: source-url
    - name: source-revision
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: react-test
            image: react-test-with-pact:node-19
            script: |-
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m

              npm install
              npm run test -- --watchAll=false
