apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: react-frontend
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: react-frontend
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: clusterBuilder
      value: full
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: "build"
      - name: BP_WEB_SERVER_ROOT
        value: "build"
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
