apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-fun
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hello-fun
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      ref:
        branch: main
    subPath: spring-cloud-function
