apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: customer-database
spec:
  ref:
    apiVersion: with.sql.tanzu.vmware.com/v1
    kind: MySQL
    name: customer-database
