apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-crawler
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hungryman
spec:
  params:
  - name: annotations
    value: 
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/sample-accelerators/hungryman
      ref:
        branch: tap-1-3