apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: mysql
spec:
  description:
    short: MySQL Database
  pool:
    group: with.sql.tanzu.vmware.com
    kind: MySQL
