apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sample-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: sample-app
spec:
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples/weatherforecast-csharp
      ref:
        branch: main
