apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: customer-database
spec:
  memory: 800Mi
  cpu: "0.8"
  storageClassName: standard
  monitorStorageClassName: standard
  storageSize: 2G
  pgConfig:
    dbname: postgresdatabase
    username: pgadmin
    appUser: pgappuser
