apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: customer-database
spec:
  description:
    short: PostgreSQL Customer Database
  pool:
    group: sql.tanzu.vmware.com
    kind: Postgres
