apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: angular-frontend
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: angular-frontend
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: clusterBuilder
      value: full
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test-angular
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: "build"
      - name: BP_WEB_SERVER_ROOT
        value: "dist"
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
