apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: postgres-1
spec:
  memory: 800Mi
  cpu: "0.8"
  storageClassName: storage-class-standard
  monitorStorageClassName: storage-class-standard
  storageSize: 2G
  pgConfig:
    dbname: development
    username: pgadmin
    appUser: pgappuser
