apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: postgres
spec:
  description:
    short: PostgreSQL Database
  pool:
    group: sql.tanzu.vmware.com
    kind: Postgres
