apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-express
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-express
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/vmware-tanzu/application-accelerator-samples
    subPath: node-express
