apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rest-service-db
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: rest-service-db
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test-java
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
  serviceClaims:
    - name: database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: customer-database
