apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sample-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: sample-app
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: weatherforecast-steeltoe
spec:
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples
      ref:
        branch: main
    subPath: weatherforecast-steeltoe
